### ISSUE TITLE
[ls-cs] Support for older versions of Windows

### ISSUE THREAD

**Issue by ghost** [RolandHughes/waylandgui#2]
Please keep supporting old Windows. CopperSpice has declared that they moved to Windows 10 as the minimum supported version, even though their code can still compile and run on Windows 7.

**Comment by ghost** [comment]
Oh I'm sorry. Wrong repository. I intended to open this issue in the ls-cs repo :facepalm:

**Comment by RolandHughes** [comment]
Once I get the rest of the Linux packages building, feel free to take a stab at Windows building. The instructions they have for building via Visual Studio 2019 should still be workable
https://www.copperspice.com/docs/cs_overview/build-msvc.html
Be sure to document what you do so it can be added to the Web site.

https://visualstudio.microsoft.com/vs/older-downloads/

22 won't install on 7.

**Comment by RolandHughes** [comment]
You may want to quickly get 2017 community edition

https://aka.ms/vs/15/release/vs_community.exe

Microsoft seems to be hiding access to it.
According to my virus scanner the file was "okay" but it just kicks off a bunch of downloads. According to my searches 2017 still supports Windows 7 (according to the installer it can compile for Windows XP too).
