### ISSUE TITLE
[ls-cs] Please reconsider the idea to be Wayland-only

### ISSUE THREAD

**Issue by ghost** [RolandHughes/waylandgui#3]
You said that you will use GLFW as the abstraction layer and GLFW supports both X11 and Wayland. So why would you go Wayland-only?

**Comment by ghost** [comment]
Oh I'm sorry. Wrong repository. I intended to open this issue in the ls-cs repo :facepalm:

**Comment by RolandHughes** [comment]
Yeah, you need to read **Runtime platform selection** on [this page](https://www.glfw.org/docs/latest/intro_guide.html#init_hints_wayland).

Probably a better way of phrasing that would be "We don't care about problems on anything other than Wayland and Vulkan." X11 isn't really being maintained anymore. Neither are many of the older Windows display systems these days.

GLFW will "fall back" but if the platform having a problem is not one of those two I'm not going to put effort into looking at it.

You are correct GLFW currently supports "just about everything" and with that as the singular abstraction layer we will support what it supports.

Having said that . . . ripping out the plug-in code for display support __and__ ripping out the display platform specific stuff higher up in the code base will be a major project. First cut will have to leave the plug-in code in place but rip out support for all others. Then we can look at how much effort it will be to rip out the plug-in logic for display packages itself.
